### ISSUE TITLE
[Bug] The text cursor is missing when setting/editing a backup name

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#28]
## Preconditions:
Have Fennec and Firefox Profile Manager installed.
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap the Create button;
3. Observe the Set backup name pop up;
### Expected behavior
There is a text cursor indicating the insertion point.
### Actual behavior
The text cursor is missing.
### Notes:
[Screenshot](https://drive.google.com/file/d/1kw26tY4pW3MVgrh7aYrmzYPgLzBvKkG2/view)
Also reproducible for Edit backup name.
### Device information
* Android device: Samsung Galaxy S8 (Android 9); Pixel (Android Q); Motorola Nexus 6 (Android 7.1.1)
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by vmbaicu** [comment]
fixed by https://github.com/mozilla-mobile/fennec-profile-manager/pull/30

**Comment by ebalazs-sv** [comment]
Hi!
This is not entirely fixed, when the Backup name field is tapped, the text cursor is not displayed. This is displayed only when the first letter is inserted.
Verified with Samsung Galaxy S8 (Android 9); Motorola Nexus 6 (Android 7.1.1) on the second build FPM received with the changes from https://github.com/mozilla-mobile/fennec-profile-manager/pull/30. Thanks!

**Comment by vmbaicu** [comment]
Should be fixed on the most recent version

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM v1.0 Build 2 Samsung Galaxy S8 (Android 9); Pixel (Android Q); Huawei Honor 8 (Android 7.0).
